ALTER TABLE users ADD COLUMN money_saved NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN level INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN xp INTEGER NOT NULL DEFAULT 0;
